version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: anewg/lamp:v1
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.3"
          memory: 1550M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    volumes:
      - /Users/linzhizhong/vagrant:/vagrant
    networks:
      - webnet
networks:
  webnet:
